linters:
  enable:
    - bodyclose
    - deadcode
    - dogsled
    - goimports
    - gosec
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - megacheck
    - misspell
    - nakedret
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck

  disable:
    - errcheck

run:
  timeout: 5m
  skip-dirs:
    - example

linters-settings:
  gocyclo:
    min-complexity: 16
  govet:
    check-shadowing: false
  nakedret:
    command: nakedret
    pattern: ^(?P<path>.*?\\.go):(?P<line>\\d+)\\s*(?P<message>.*)$

issues:
  # The default exclusion rules are a bit too permissive, so copying the relevant ones below
  exclude-use-default: false

  exclude:
    - parameter .* always receives